project:
  type: website
  output-dir: docs

website:
  title: "BAT3301 Operations Management"
  sidebar:
    background: primary
    logo: "images/logo_new.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://ianliu0313.github.io/BAT3301_Fall24/
        text: Home Site
      - icon: house-fill
        href: https://canvas.trinity.edu/
        text: Canvas Trinity University
    style: docked
    contents:
      - href: index.qmd
        text: Home
      - href: syllabus.qmd
        text: Syllabus
      - href: schedule.qmd
        text: Schedule
        
format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute:
  freeze: auto

