---
title: "Syllabus"

jupyter: python3
---

**BAT 3301 – Operations Management Syllabus**

<hr>

## Course Learning Objectives

By the end of this course, students will be able to:

- Understand the importance and scope of the OM function.
- Understand the quantitative techniques that impact operations management decision-making (e.g., demand forecasting, facility location, inventory management) to illustrate how these tools provide a basis for monitoring personnel and organizational performance and ultimately are the basis for problem-solving.
- Understand the latest and more widespread trends within the OM function. 
- Help future managers in other areas identify the interfaces with OM and effectively communicate with operations specialists.
- Establish some familiarity with conducting research in the OM area. - “Research” here implies the process of preparing for OM-related job interviews. 
- Add a couple of highlighted points (project, business models/ideas learned, etc.) on their resumes.
- Handle OM-related interview questions.
  
## Required Textbook

Our class is self-contained to save you **$**. All teaching materials will be availableon Canvas. Textbooks that I'm using to prepare the lectures are listed in the table below for your reference. The books are also on reserve at the circulation desk in the library. As an alternative to purchasing or renting the textbook, you may check it out from the library for 2 hours at a time to do your readings/homework. Unfortunately, the library does not have an E-version for this textbook. You will have to borrow the physical book if you do not plan to buy or rent the textbook. The e-version of the book may be available online, let me know if you have trouble finding the book. Other OM-related readings will be required to read before lectures. 

All books are available online. Physical and electronic copies are also available for purchase.

| Book Title                 |  Authors          |  Publisher and Edition Number                                 |
|------------------------------------|------------------|------------------|
| [Operations Management ](https://www.pearson.com/store/en-us/pearsonplus/p/9780135662083.html?utm_source=google&utm_medium=cpc&utm_campaign=dsa_url_contains&gclsrc=aw.ds&gad_source=1&gbraid=0AAAAADnfL3uazOkeluag6H_KXrF1y7aFg)                            | Heizer, Render, and Munson       | Pearson, 9th or Later Editions     |
| [Operations And Supply Chain Management](https://www.mheducation.com/highered/product/9781266292804?cid=ppc%7CHE%7CPDP_Students_Dynamic%7CGoogle%7C&gad_source=1&gbraid=0AAAAADimpZPAC64ok3ULxP-uHGAw0-um1&gclid=EAIaIQobChMImuHKouWGiAMVlFN_AB3npAtsEAAYASAAEgKB0_D_BwE) | Jacobs & Chase | McGraw Hill, 5th or Later Editions |

  
## Assurance of Learning

Learning goals derived from the department’s mission statement drive the delivery of this course. The affirmation of learning will be ascertained, if applicable, through an evaluation rubric that meets the AACSB Assurance of Learning Standards.

## General Course Policies

- **CLASS PREPARATION**: Classes are designed to supplement the reading materials (textbooks, course slides, and required readings). Therefore, lectures will not necessarily address the text directly and may not cover all the details in the reading materials. Students must read assigned materials as part of the learning effort. Reading the assigned materials is a good way to cultivate your critical thinking ability and help better follow lectures. Bottom line: Read course slides and required readings.
- **PARTICIPATION**: Participation in classes is expected for all students, and a lack of participation will impact the grade (see evaluation). Students need to inform the instructor before the class about any anticipated excused absences. See the university attendance guidelines for the definition of excused absences.
- **LATE SUBMISSIONS**: DO NOT wait until the last minute to submit your assignments as it is always possible to encounter network or computer problems. You do have a grace period of TWO day for late submissions without any penalties, any late work after the grace period won’t be accepted. Please come to my office hour if you need help on lectures, assignments etc.
- **WRITING**: Professional writing is expected for all assignments, tests, or presentations. You can utilize the writing center if you need assistance. Grammarly and any other similar tools are recommended.
- **COMMUNICATION**: Course communication will be done through Canvas and/or email. Be sure to check both regularly for announcements, updates, etc. You are responsible for any content provided. Students need to inform the instructor before the class about any anticipated excused absences. See the university attendance guidelines for the definition of excused absences. Leaving the lecture early without permission is automatically an unexcused absence. While I check my email regularly, do not expect as quick a response past 10 pm during the week or on weekends. I will do my best to respond to emails within 24 hours during the week, and within 48 hours on the weekend.
- **EMAIL CONVENTIONS**: Please put the course name and code in the email subject. Any email without a formal and proper subject may automatically be directed to spam or trash.
- **EXAM DATES**: Please plan your travel arrangements carefully to avoid conflicts with exam dates. If you have unavoidable commitments that necessitate taking exams on different dates, please inform me well in advance. Note that such accommodations will be considered on a case-by-case basis and are not guaranteed.


## Grading and Evaluation Criteria

It is required to finish the the assigned readings before coming to the lectures. It is further recommended that after the class or before the next class you review the previous lecture, work on any assigned problems, and bring any questions you may have. Repetition is important in this type of course. Reading the materials prior to class will assist you in understanding the lecture and the class exercises. You also need to write your own answers. Last-minute cramming for the exams tends to result in lack of understanding and a lackluster performance. The final course grade will be calculated as follows:

<center>

| Category                          | Percentage |
|-----------------------------------|------------|
| Participation/Notes Submissions   | 5%         |
| Mini Essays                       | 10%        |
| Group Project                     | 10%        |
| Exam 01                           | 15%        |
| Exam 02                           | 15%        |
| Exam 03                           | 20%        |
| 7 Homeworks                       | 25%        |


```{python}
#| echo: false

import matplotlib.pyplot as plt

# Data to plot
labels = ['Participation/Notes Submissions',' Mini Essays','Group Project','Exam 01','Exam 02','Exam 03','7 Homeworks']
sizes = [5,10,10,15,15,20,25]  # Percentages
colors = ['gold', 'yellowgreen', 'lightcoral', 'lightskyblue', 'lightgreen', 'purple', 'red']

# Plot
plt.figure(figsize=(5,5))  # Making the figure a bit larger
plt.pie(sizes, labels=labels, colors=colors, autopct='%0.0f%%',startangle=140)

plt.axis('equal')  # Equal aspect ratio ensures that pie is drawn as a circle.
plt.title('Grade Composition', pad = 20)
plt.show()

```


## Grade Distribution

Grades will be assigned using the following distribution:

- A (93.0 – 100), A- (90.0 – 92.9)
- B+ (87.0 – 89.9), B (83.0 – 86.9), B- (80.0 – 82.9)
- C+ (77.0 – 79.9), C (73.0 – 76.9), C- (70.0 – 72.9)
- D+ (67.0 – 69.9), D (60.0 – 66.9)

## Coursework Requirements

### Exams

There will be THREE exams. Through these exams you have the opportunity to demonstrate what you've learned in the course thus far. 1 page of letter-sized cheat sheet is allowed for exams. A calculator is allowed as well. 

### Homework & Mini-Essays

There will be 7 homework (the lowest 1 grade will be dropped), and 10 300-word mini essays in this course. Mini-essays are designed to help you understand cutting-edge business models and prepare to ace job interviews in the future. There will be a few random quizzes and other in-class activities in this course. In-class activities are designed to help you learn the material, and you are encouraged to complete them. 

Homework assignments are posted on Canvas and should be legible, complete, and **typed**. Computational steps and details must be shown to earn full credits. Homework assignments are to be turned in at 11:59 PM on their due dates. **You are allowed a grace period of two day for late submissions**, but any late submissions after that will not be accepted. 

If there are extreme circumstances which prevent you from completing the assignment on time, please email me before the due date. Please familiarize yourself with the Canvas system early in the semester. If you are not sure if an assignment has submitted correctly, you may email me with your attached homework as proof that it has been completed by the deadline.


### In-Class Participation and Attendance

The attendance portion of the grade is made up of several components:

- Being physically present in class.
- **Not distracting others while in class**. This extends to other students. If your behavior impedes the learning environment of other students, you may be asked to leave the classroom and it will be reflected in your grade.
- Completion of assigned coursework, including in-class activities, notes submissions and in-class quizzes.

In-Class Participation is essential for students’ engagement and learning experience. Following University policy, students with 4 or more absences may be dropped from the course before the withdrawal deadline or get an F for the final grade according to the University policies listed under the Course of Study Bulletin or may see their final grade affected.

In specific, you will need to complete the following task to earn the credits for In-Class Participation/Attendance:
- Submit your notes via Canvas at the end of the day of each lecture. The format of the notes doesn't matter, the submission is counted as your attendance. If you can't make it to the class due to unavoidable reasons, please do NOT make any submissions. 

### Examinations

**THREE** examinations will be given to evaluate your knowledge of the topics covered in lectures, readings, and assignments, as well as the ability to interpret results. Make-up exams will not be offered unless the absence is for a university sanctioned event (excuse notes must be received before semester examinations) or the instructors deem that the absence was permissible due to extreme extenuating circumstances.

Accommodated testing can be taken in the Accommodated Testing Center between the hours of 8:30 a.m. and 4:30 p.m. on the exam dates. You must utilize the testing center if you want any allotted extra time for your exams. Students are responsible for scheduling their exams with the ATC. Students must take exams at the ATC on or before the scheduled exam dates.

### Accommodations

Trinity University is committed to providing equal access and equal opportunity to students with disabilities. As a sign of that commitment, the office of Student Accessibility Services (SAS) is to assist students who seek accommodations. Information is available at: https://new.trinity.edu/campuslife/campus-services/student-accessibility-services. Please let me know if you need any assistance as early as possible.

Accommodated testing can be taken in the Accommodated Testing Center between the hours of 8:30 a.m. and 4:30 p.m. on the exam dates. You must utilize the testing center if you want any allotted extra time for your exams. Students are responsible for scheduling their exams with the ATC. Students must take exams at the ATC on or before the scheduled exam dates.

### Grades Boosting Opportunities?

Yes. I plan to drop **ONE** lowest homework grades by the end of the semester. At least **TWO** extra credit opportunities will be offered throughout the semester. Stay tuned :)

### Final Project

For the final project in this course, students will be asked to use what they have learned to solve a practical solution to a ‘real world’ problem. The final project is designed to integrate the knowledge and skills acquired throughout the semester. In groups of 5-6, students will select a real-world problem of their choice and propose a research question that can be addressed using the knowledge covered throughout the course, or read, study and present a research paper in Operations Management that has a good citation number. More discussions and information will be offered after Exam 2.

## Academic Honesty and Policy on the Usage of Generative AI (IMPORTANT)

The values of honesty, scholarship and the pursuit of excellence are central to the mission of Trinity University. The Academic Honor Code is the system through which Trinity students uphold these values by assuming individual responsibility for integrity. An environment that encourages personal responsibility facilitates one of the highest aims of education, the free pursuit of knowledge. The Academic Honor Code and related matters can be found at: https://inside.trinity.edu/academics/academic-honor-code:

<center>

**"On my honor, I have neither given nor received any unauthorized assistance on this work"**


Generative AI (ChatGPT, Google Bard, Facebook’s LLaMa, Microsoft’s Copilot) is permitted to use ONLY to validate your answers and/or to help you debug/improve the code AFTER you have finished your assignments. You **CANNOT** use them to pursue answers or write the code for you. I have a background in Computer Science, so I **DO** have tools to check if you have used Generative AI for your work or not. So be careful. I’m watching ya!


## Sick Policy
Your health and the well-being of others are also our priorities. If you are experiencing any signs of illness (e.g., fever, nausea, heavy cough, etc.), please do not attend class. Stay home and only return once you are completely symptom-free. If you are unable to attend class due to illness, send me an email as soon as possible to inform me of your situation. 

While your health comes first, you are still responsible for completing any required submissions, quizzes, or assignments on time. If your illness impacts your ability to meet deadlines, communicate with me promptly to discuss possible accommodations.

## Other Resources 

Trinity faculty hold students to the highest academic standards, but we also know that the very best students seek out help when necessary. The following resources are in place to support your academic success; learn more at gotu.us/success: 

- Academic Success: time management, student skills, test anxiety, note taking, and tutoring C
- Career Services: major exploration and career guidance 
- Counseling Services: mental health concerns and mental health referrals
- Quantitative Reasoning and Skills Center: quantitatively demanding coursework
- Student Accessibility Services: accommodations for a diagnosed disability 
- Wellness Center: nutrition, sleep, and stress management 
- Writing Center: starting a paper, finding a thesis, drafting and editing

## Electronic Recordings of Classroom Instruction

Please be aware that all classroom instruction, including student participation in classroom activities, is subject to recording and dissemination on the University’s secure course management system (Canvas). The recordings will be made available only to students enrolled in the course to facilitate online learning and review. Students are expressly prohibited from capturing or copying classroom recordings by any means unless approved; violations will be subject to disciplinary action. Instructors who wish to use a recording outside of class must obtain the written consent of any students who are personally identifiable in the recording.

## Required Video Sharing/Online Proctoring

The instructor reserves the right to use a Respondus Monitor or a similar tool on your computer while taking exams. Detailed instructions for use and downloading of the proctoring tool will be provided in an email. This software allows for online proctoring by monitoring individuals on their computer webcam, as well as video analytics to identify potential cheating. Any recordings will be treated as an education record subject to FERPA protections.

## Sexual Misconduct, Required Reporting, and Title IX

As a Responsible Employee who is committed to creating an environment where every member of our community can thrive, I want to let you know that I am a Mandatory Reporter. What that means is that I am required to report any instances of sexual misconduct, including sexual harassment, non-consensual sexual intercourse, non-consensual sexual contact, sexual exploitation, intimate partner violence, stalking, and related retaliation that I am aware of to the Title IX Coordinator. So, if you share information with me about any incidents that implicate the Sexual Misconduct or Anti-Harassment Policies, I am required to report all information to the Title IX Coordinator to make sure you have information about support resources and complaint resolution options. My report does not initiate the complaint process, and you are in control over how you choose to engage with our Title IX Coordinator. If you or someone you know has experienced sexual misconduct, including sexual harassment, I encourage you to share this information directly with the Title IX Coordinator or one of the individuals who has been designated as a confidential resource on campus. The reporting form is available here.


## Policy on Syllabus Changes and Contractual Obligations

This syllabus and course outline are subject to change in the discretion of the instructor during the course of the semester. Changes may be necessary because of student’s specific interest, the general class progression and emerging topics of interest. If any changes are implemented, they will be announced in class and/or posted to Canvas.

## Important dates
- **Jan 10**: Add/Drop Begins
- **Jan 15**: Classes Begin	
- **Jan 20**: MLK Holiday
- **Jan 23**: Add/Drop Ends
- **Feb 05**:  Last Day Opt Pass/Fail
- **Mar 08-16**: Spring Break
- **Apr 02**: Last Day to Withdraw With a W
- **Apr 18**: Class Recess
- **TBA**: Final Exam(Location TBA)
